CREATE TABLE IF NOT EXISTS ecommerce.order_items(
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
quantity INTEGER NOT NULL,
order_id BIGINT NOT NULL,
product_id BIGINT NOT NULL,

CONSTRAINT fk_order FOREIGN KEY (order_id) REFERENCES ecommerce.orders(id),
CONSTRAINT fk_product FOREIGN KEY (product_id) REFERENCES ecommerce.products(id)
);